import { ApiProperty } from '@nestjs/swagger';
import { IsIn } from 'class-validator';
import { PAYMENT_METHOD_TOKENS } from '../providers/payment-method-tokens';

export class RetryPaymentDto {
  @ApiProperty({
    enum: PAYMENT_METHOD_TOKENS,
    example: 'tok_test_success',
    description: 'The next attempt number and idempotency key are generated by the server.',
  })
  @IsIn(PAYMENT_METHOD_TOKENS, {
    message: 'paymentMethodToken must be one of the supported simulation tokens',
  })
  paymentMethodToken!: string;
}
