export const CURRENCY = 'USD';

export const FREE_SHIPPING_THRESHOLD_CENTS = 10_000;

export const STANDARD_SHIPPING_CENTS = 1_500;

export const CONSOLIDATED_SHIPPING_CENTS = 2_500;

export const MAX_QUANTITY_PER_ITEM = 20;

export const MAX_ITEMS_PER_ORDER = 20;
